name: Site Automation

on:
  schedule:
    # تولید محتوای بلاگ - هر روز ساعت 06:00 و 18:00
    - cron: "0 6,18 * * *"
    # بهینه‌سازی سایت - هر روز ساعت 02:00
    - cron: "0 2 * * *"
  workflow_dispatch: # اجرای دستی در صورت نیاز

jobs:
  site-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests openai python-dotenv

      - name: Run Blog Automation
        if: contains(github.event.schedule, '0 6') || contains(github.event.schedule, '0 18')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ secrets.GITHUB_OWNER }}
          GITHUB_REPO: ${{ secrets.GITHUB_REPO }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TASK: blog
        run: python gpt_content_update.py

      - name: Run Site Optimization
        if: contains(github.event.schedule, '0 2')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ secrets.GITHUB_OWNER }}
          GITHUB_REPO: ${{ secrets.GITHUB_REPO }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TASK: update
        run: python gpt_content_update.py
